table _Medidas
	lineageTag: 92e81126-6863-43b4-b14b-db55a53178d5

	measure '$ Faturamento_Total' = ```
			// Faturamento Total 
			SUMX(
			    PBI_Fato_Vendas,
			        PBI_Fato_Vendas[QtdPedido] * PBI_Fato_Vendas[PreçoUnitario]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b4bef239-d4f9-40d8-b118-d92daca67915

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Faturamento_Liquido' =
			// qtd * preço *(1- % desconto)
			SUMX(
			    PBI_Fato_Vendas,
			    PBI_Fato_Vendas[QtdPedido] * PBI_Fato_Vendas[PreçoUnitario] * (1- PBI_Fato_Vendas[DescontoUnitario]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 77faa5b4-99b8-468c-bc30-3222f38decef

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Vendas Internet B2C' =
			
			CALCULATE(
			    [$ Faturamento_Liquido],
			         PBI_Fato_Vendas[OnlineOrderFlag] = 1
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3a618bce-3648-4252-acdc-937364be114e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Vendas Corporativas B2B' =
			
			CALCULATE(
			    [$ Faturamento_Liquido],
			         PBI_Fato_Vendas[OnlineOrderFlag] = 0
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c7bf39e4-4464-457c-8b9f-2d77aea95bb9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '! Cabeçalho Painel' = "Acompanhamento Vendas"
		lineageTag: f02bc5b2-6365-4680-8687-f83843c0345d

	measure 'Quantidade Total Vendida' =
			
			SUM(PBI_Fato_Vendas[QtdPedido])
		formatString: 0
		lineageTag: ab37ba4a-218c-4c2c-b4cd-cc0ae39e7dc2

	measure 'Status Cobertura Estoque' = ```
			
			VAR vQtdVendida = [Quantidade Total Vendida]
			VAR vEstoqueAtual =  SUM(PBI_Dim_Estoque[Estoque Total])
			VAR vSaldo = vEstoqueAtual - vQtdVendida
			
			RETURN 
			
			IF(
			    ISBLANK(vQtdVendida), 
			    BLANK(),
			    IF(
			        vSaldo > 0 , 
			        "Com Cobertura",
			        "Sem Cobertura"
			    )
			)
			```
		lineageTag: f847d68c-cd72-4844-aeec-4e8b8289b105

	measure '$ Faturamento Sem Cobertura' =
			
			CALCULATE(
			    [$ Faturamento_Liquido],
			        FILTER(
			            VALUES(
			                PBI_Dim_Produto[ProductID]),
			                [Status Cobertura Estoque] = "Sem Cobertura"
			        )
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 75e86481-83fb-49cf-a8f4-195e8db824e6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Faturamento Com Cobertura' =
			
			CALCULATE(
			    [$ Faturamento_Liquido], // Substitua pelo nome real da sua medida de faturamento
			    FILTER(
			        VALUES('PBI_Dim_Produto'[ProductID]),
			        [Status Cobertura Estoque] = "Com Cobertura"
			    )
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 5ca24397-3811-4c5c-aa8e-d4bf95b7833b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition _Medidas = m
		mode: import
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Origem,{"Coluna 1"})
				in
				  #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

