table PBI_Fato_Vendas
	lineageTag: ed51dd8a-1e04-4fc7-aba6-0f678d58d194

	column SalesOrderID
		dataType: int64
		formatString: 0
		lineageTag: a0d55fd1-662b-4b47-992e-9026da6d9883
		summarizeBy: count
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column DataPedido
		dataType: dateTime
		formatString: Long Date
		lineageTag: c008d618-90c6-47e9-87cf-86f77a2cc38c
		summarizeBy: none
		sourceColumn: DataPedido

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 3e1c5e8c-e321-4762-b76d-0b51f67e7f51
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column SalesPersonID
		dataType: int64
		formatString: 0
		lineageTag: da2e1607-a5ee-4f23-bfb0-7243adf1f240
		summarizeBy: count
		sourceColumn: SalesPersonID

		annotation SummarizationSetBy = Automatic

	column TerritoryID
		dataType: int64
		formatString: 0
		lineageTag: aef5c73c-50f0-4242-9501-3c78d2ad1aa8
		summarizeBy: count
		sourceColumn: TerritoryID

		annotation SummarizationSetBy = Automatic

	column OnlineOrderFlag
		dataType: int64
		formatString: 0
		lineageTag: 7ea81846-9ffc-43ea-8a62-8b1ef8cb66d4
		summarizeBy: sum
		sourceColumn: OnlineOrderFlag

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: e872cce6-16e1-4985-817f-0e0f311edcf1
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column QtdPedido
		dataType: int64
		formatString: 0
		lineageTag: c59f62d8-70c6-43a9-9ad5-8f3ff385a6b5
		summarizeBy: sum
		sourceColumn: QtdPedido

		annotation SummarizationSetBy = Automatic

	column PreçoUnitario
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 12deb36e-6573-4c75-98c3-8c07c4b80ff6
		summarizeBy: sum
		sourceColumn: PreçoUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DescontoUnitario
		dataType: double
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 29143a94-999f-4919-841b-eb75692a7396
		summarizeBy: sum
		sourceColumn: DescontoUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Tipo Venda'
		dataType: string
		lineageTag: 4dee7357-3bfc-4837-84c9-0ad08f54bcb9
		summarizeBy: none
		sourceColumn: Tipo Venda

		annotation SummarizationSetBy = Automatic

	partition PBI_Fato_Vendas = m
		mode: import
		source =
				let
				  Origem = Sql.Database("LENOVO_JOTA\SQLEXPRESS", "AdventureWorks2025"),
				  #"Navegação 1" = Origem{[Schema = "dbo", Item = "PBI_Fato_Vendas"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Navegação 1",{{"DataPedido", type date}, {"DescontoUnitario", type number}, {"OnlineOrderFlag", Int64.Type}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Tipo Venda", each if [OnlineOrderFlag] = 0 then "B2B" else if [OnlineOrderFlag] = 1 then "B2C" else null, type text)
				in
				    #"Coluna Condicional Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

