table PBI_Fato_Vendas
	lineageTag: ed51dd8a-1e04-4fc7-aba6-0f678d58d194

	column SalesOrderID
		dataType: int64
		formatString: 0
		lineageTag: a0d55fd1-662b-4b47-992e-9026da6d9883
		summarizeBy: count
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column DataPedido
		dataType: dateTime
		formatString: Long Date
		lineageTag: c008d618-90c6-47e9-87cf-86f77a2cc38c
		summarizeBy: none
		sourceColumn: DataPedido

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 3e1c5e8c-e321-4762-b76d-0b51f67e7f51
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column SalesPersonID
		dataType: int64
		formatString: 0
		lineageTag: da2e1607-a5ee-4f23-bfb0-7243adf1f240
		summarizeBy: count
		sourceColumn: SalesPersonID

		annotation SummarizationSetBy = Automatic

	column TerritoryID
		dataType: int64
		formatString: 0
		lineageTag: aef5c73c-50f0-4242-9501-3c78d2ad1aa8
		summarizeBy: count
		sourceColumn: TerritoryID

		annotation SummarizationSetBy = Automatic

	column OnlineOrderFlag
		dataType: int64
		formatString: 0
		lineageTag: 7ea81846-9ffc-43ea-8a62-8b1ef8cb66d4
		summarizeBy: sum
		sourceColumn: OnlineOrderFlag

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: e872cce6-16e1-4985-817f-0e0f311edcf1
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column QtdPedido
		dataType: int64
		formatString: 0
		lineageTag: c59f62d8-70c6-43a9-9ad5-8f3ff385a6b5
		summarizeBy: sum
		sourceColumn: QtdPedido

		annotation SummarizationSetBy = Automatic

	column PreçoUnitario
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 12deb36e-6573-4c75-98c3-8c07c4b80ff6
		summarizeBy: sum
		sourceColumn: PreçoUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DescontoUnitario
		dataType: double
		formatString: #,0.00
		lineageTag: 29143a94-999f-4919-841b-eb75692a7396
		summarizeBy: sum
		sourceColumn: DescontoUnitario

		annotation SummarizationSetBy = Automatic

	column 'Tipo Venda'
		dataType: string
		lineageTag: 4dee7357-3bfc-4837-84c9-0ad08f54bcb9
		summarizeBy: none
		sourceColumn: Tipo Venda

		annotation SummarizationSetBy = Automatic

	column 'Faixa Margem Operacional' =
			
			VAR PrecoPraticado = PBI_Fato_Vendas[PreçoUnitario]
			VAR Desconto = PBI_Fato_Vendas[DescontoUnitario]
			VAR PrecoLiquido = PrecoPraticado * (1 - Desconto)
			VAR Custo = RELATED(PBI_Dim_Produto[Custo_Padrao])
			VAR MargemLinha = DIVIDE(PrecoLiquido - Custo, PrecoLiquido)
			
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(MargemLinha), "Sem Margem",
			    MargemLinha < 0.20, "Pessima",
			    MargemLinha >= 0.20 && MargemLinha < 0.28, "Ruim",
			    MargemLinha >= 0.28 && MargemLinha < 0.35, "Regular",
			    MargemLinha >= 0.35 && MargemLinha < 0.50, "Boa",
			    MargemLinha >= 0.50, "Otima"
			)
		lineageTag: 0968f433-80bf-4606-9544-6dfb48e73b6c
		summarizeBy: none
		sortByColumn: 'Ordem Faixa Margem Operacional'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Lucro Produto' =
			
			-- 1. Descobre o preço real que o cliente pagou com o desconto aplicado
			VAR PrecoLiquido = PBI_Fato_Vendas[PreçoUnitario] * (1 - PBI_Fato_Vendas[DescontoUnitario])
			
			-- 2. Subtrai o custo desse preço que já está líquido
			RETURN
			PrecoLiquido - RELATED(PBI_Dim_Produto[Custo_Padrao])
		formatString: #,0.00
		lineageTag: ad7d4fac-81e3-419f-aaab-81f78c075b85
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Ordem Faixa Margem Operacional' =
			
			VAR PrecoPraticado = PBI_Fato_Vendas[PreçoUnitario]
			VAR Desconto = PBI_Fato_Vendas[DescontoUnitario]
			VAR PrecoLiquido = PrecoPraticado * (1 - Desconto)
			VAR Custo = RELATED(PBI_Dim_Produto[Custo_Padrao])
			VAR MargemLinha = DIVIDE(PrecoLiquido - Custo, PrecoLiquido)
			
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(MargemLinha), 0,
			    MargemLinha < 0.20, 1,
			    MargemLinha >= 0.20 && MargemLinha < 0.28, 2,
			    MargemLinha >= 0.28 && MargemLinha < 0.35, 3,
			    MargemLinha >= 0.35 && MargemLinha < 0.50, 4,
			    MargemLinha >= 0.50, 5
			)
		formatString: 0
		lineageTag: 34108d2e-83b7-44e6-82fa-13196a9304a2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition PBI_Fato_Vendas = m
		mode: import
		queryGroup: Fato
		source =
				let
				  Origem = Sql.Database("LENOVO_JOTA\SQLEXPRESS", "AdventureWorks2025"),
				  #"Navegação 1" = Origem{[Schema = "dbo", Item = "PBI_Fato_Vendas"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Navegação 1",{{"DataPedido", type date}, {"DescontoUnitario", type number}, {"OnlineOrderFlag", Int64.Type}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Tipo Venda", each if [OnlineOrderFlag] = 0 then "B2B" else if [OnlineOrderFlag] = 1 then "B2C" else null, type text)
				in
				    #"Coluna Condicional Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

